Comments
slacgismo/pv-system-profiler pull request #17
Opened 2021-08-02 20:07 UTC by alejandro350

2021-08-04 21:02 UTC, bmeyers requested changes

2021-08-04 21:11 UTC, bmeyers commented on pvsystemprofiler/latitude_study.py
> +    def prepare_estimation(self, matrix_id=None, daytime_threshold=0.001,
call this `prepare_input_data`. have function return a 2-tuple of `(hours_daylight, delta)`

2021-08-04 21:20 UTC, bmeyers commented on pvsystemprofiler/algorithms/latitude/estimation.py
> +def estimate_latitude(hours_daylight, delta):
there is only one way of estimating latitude, so this should be a pass-through function

2021-08-04 21:21 UTC, bmeyers commented on pvsystemprofiler/algorithms/latitude/calculation.py
> +
bring this file into alignment with `longitude/calculation.py`

2021-08-04 21:22 UTC, bmeyers commented on pvsystemprofiler/algorithms/longitude/calculation.py
fix names here so that the two functions don't have identical names

2021-08-04 21:50 UTC, bmeyers requested changes

2021-08-04 21:50 UTC, bmeyers commented on pvsystemprofiler/estimator.py
>                             eot_calculation='duffie',
needs to use `longitude/estimate.py`

2021-08-04 21:50 UTC, bmeyers commented on pvsystemprofiler/estimator.py
> +        self.latitude = self._cal_lat_helper(hours_daylight_filtered)
this can be simplified

2021-08-04 21:50 UTC, bmeyers commented on pvsystemprofiler/estimator.py
>      def estimate_longitude(self, estimator='fit_l1',
data filtering should happen in this function, not in lower-level helper functions

2021-08-04 21:50 UTC, bmeyers commented on pvsystemprofiler/longitude_study.py
>  The following configurations can be run:
this is the explanation that `latitude_study.py` could benefit from

2021-08-04 21:50 UTC, bmeyers commented on pvsystemprofiler/scripts/latitude_script.py
> +                passes_pipeline = run_failsafe_pipeline(df, dh, sys_tag, fix_time_shifts, time_zone_correction)
move data handler instantiation into `run_failsafe_pipeline`. check downstream effects to other scripts

2021-08-06 18:33 UTC, bmeyers requested changes

2021-08-06 18:33 UTC, bmeyers commented on pvsystemprofiler/scripts/longitude_script.py
>                          dh.fix_dst()
handling of the data handler needs to be fixed. currently, this data handler from the outer scope does not get the pipeline run on it

2021-08-06 18:33 UTC, bmeyers commented on pvsystemprofiler/scripts/latitude_script.py
>                      if manual_time_shift == 1:
handling of data handler needs to be fixed

2021-08-06 18:33 UTC, bmeyers commented on pvsystemprofiler/scripts/modules/script_functions.py
>      return True
need to return the data handler object here so that it is available in the outer scope

2021-08-06 18:33 UTC, bmeyers commented on pvsystemprofiler/utilities/tools.py
>      return (doy)
is this being used?

2021-08-09 20:17 UTC, alejandro350 commented
Docstrings added, updated estimator class.

2021-08-09 20:18 UTC, merged